[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:all"
  targetPort = 5173

[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.stripe.com https://*.google.com https://apis.google.com https://accounts.google.com https://*.gstatic.com https://*.firebaseapp.com https://www.googletagmanager.com;
      connect-src 'self' https://*.stripe.com https://*.google.com https://*.googleapis.com https://*.gstatic.com https://*.firebaseapp.com https://*.cloudfunctions.net https://api.docuseal.com https://*.docuseal.com wss: data: blob: https://identitytoolkit.googleapis.com https://securetoken.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.gstatic.com;
      img-src 'self' data: https://* blob:;
      frame-src 'self' https://*.stripe.com https://*.google.com https://accounts.google.com https://*.firebaseapp.com https://*.docuseal.com blob:;
      font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com;
      worker-src 'self' blob:;
      child-src 'self' blob:;
      object-src 'none';
      media-src 'self'"""
    Cross-Origin-Resource-Policy = "same-site"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "credentialless"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  DOCUSEAL_API_URL = "https://api.docuseal.com"